export const defaultHealthData = {
  profile: {
    name: "New Patient",
    age: "",
    gender: "",
    height: "",
    bloodType: "",
    allergies: "",
    conditions: "",
    emergencyName: "",
    emergencyPhone: "",
    emergencyRel: "",
    doctor: "",
    clinic: "",
  },
  vitals: [],
  meds: [],
  appointments: [],
  meals: [],
  exercise: [],
  symptoms: [],
};

export const sampleHealthData = {
  profile: {
    name: "Rachana Dutta",
    age: 34,
    gender: "Female",
    height: 163,
    bloodType: "B+",
    allergies: "Dust, pollen, shellfish",
    conditions: "Migraine, mild iron deficiency, seasonal allergies",
    emergencyName: "Priyesh Kumar",
    emergencyPhone: "+91 7061449907",
    emergencyRel: "Partner",
    doctor: "Dr. James Patel",
    clinic: "Metro Health Center",
  },
  vitals: [
    { date: "May 26", hr: 72, bp: "118/76", spo2: 98, temp: 36.6, rr: 14, weight: 65.2 },
    { date: "May 25", hr: 75, bp: "120/78", spo2: 97, temp: 36.8, rr: 15, weight: 65.4 },
    { date: "May 24", hr: 69, bp: "116/74", spo2: 98, temp: 36.5, rr: 13, weight: 65.1 },
    { date: "May 23", hr: 78, bp: "122/80", spo2: 96, temp: 36.9, rr: 16, weight: 65.7 },
    { date: "May 22", hr: 70, bp: "117/75", spo2: 99, temp: 36.4, rr: 14, weight: 65.5 },
    { date: "May 21", hr: 82, bp: "126/82", spo2: 97, temp: 37.0, rr: 16, weight: 65.9 },
    { date: "May 20", hr: 74, bp: "119/77", spo2: 98, temp: 36.7, rr: 15, weight: 66.0 },
    { date: "May 19", hr: 71, bp: "115/73", spo2: 99, temp: 36.5, rr: 13, weight: 66.1 },
  ],
  meds: [
    { id: 1, name: "Ferrous Sulfate", dose: "325mg", freq: "Once daily", time: "8:00 AM", taken: true, category: "Iron Deficiency" },
    { id: 2, name: "Cetirizine", dose: "10mg", freq: "Once daily", time: "9:00 PM", taken: true, category: "Allergy" },
    { id: 3, name: "Riboflavin", dose: "400mg", freq: "Once daily", time: "Morning", taken: true, category: "Migraine" },
    { id: 4, name: "Magnesium Glycinate", dose: "200mg", freq: "Once daily", time: "Bedtime", taken: false, category: "Migraine" },
    { id: 5, name: "Vitamin D3", dose: "1000 IU", freq: "Once daily", time: "With lunch", taken: true, category: "Supplement" },
    { id: 6, name: "Omega-3", dose: "1000mg", freq: "Once daily", time: "With dinner", taken: false, category: "Supplement" },
  ],
  appointments: [
    { id: 1, doctor: "Dr. James Patel", specialty: "General Physician", date: "2026-06-04", time: "10:30", type: "Routine Checkup", location: "Metro Health Center", notes: "Review ferritin and vitamin D reports" },
    { id: 2, doctor: "Dr. Sarah Chen", specialty: "Neurologist", date: "2026-06-12", time: "14:00", type: "Follow-up", location: "City Neuro Clinic", notes: "Migraine frequency follow-up" },
    { id: 3, doctor: "Dr. Lisa Torres", specialty: "Dietitian", date: "2026-06-18", time: "11:15", type: "Consultation", location: "Wellness Nutrition Studio", notes: "Protein and iron-rich meal plan" },
    { id: 4, doctor: "Metro Diagnostics", specialty: "Lab Work", date: "2026-06-24", time: "08:00", type: "Lab Work", location: "Metro Diagnostics", notes: "CBC, ferritin, lipid panel" },
  ],
  meals: [
    { id: 1, name: "Oatmeal, banana, chia", type: "Breakfast", kcal: 390, protein: 13, carbs: 64, fat: 10, time: "07:45" },
    { id: 2, name: "Spinach omelet", type: "Breakfast", kcal: 310, protein: 24, carbs: 8, fat: 20, time: "08:20" },
    { id: 3, name: "Grilled chicken quinoa bowl", type: "Lunch", kcal: 540, protein: 42, carbs: 52, fat: 18, time: "12:35" },
    { id: 4, name: "Rajma, rice, cucumber salad", type: "Lunch", kcal: 610, protein: 24, carbs: 92, fat: 14, time: "13:10" },
    { id: 5, name: "Greek yogurt with berries", type: "Snack", kcal: 180, protein: 17, carbs: 22, fat: 3, time: "16:00" },
    { id: 6, name: "Apple with peanut butter", type: "Snack", kcal: 240, protein: 7, carbs: 28, fat: 12, time: "17:30" },
    { id: 7, name: "Salmon, sweet potato, greens", type: "Dinner", kcal: 620, protein: 45, carbs: 48, fat: 26, time: "20:05" },
    { id: 8, name: "Paneer tikka wrap", type: "Dinner", kcal: 520, protein: 30, carbs: 46, fat: 24, time: "20:40" },
  ],
  exercise: [
    { id: 1, type: "Running", duration: 35, kcal: 290, date: "Today", intensity: "Moderate", notes: "Easy pace, felt steady" },
    { id: 2, type: "Yoga", duration: 45, kcal: 160, date: "Today", intensity: "Low", notes: "Evening mobility" },
    { id: 3, type: "Cycling", duration: 60, kcal: 420, date: "Yesterday", intensity: "High", notes: "Intervals on stationary bike" },
    { id: 4, type: "Walking", duration: 50, kcal: 210, date: "May 24", intensity: "Low", notes: "Post-lunch walk" },
    { id: 5, type: "Weight Training", duration: 40, kcal: 240, date: "May 23", intensity: "Moderate", notes: "Lower body strength" },
    { id: 6, type: "Pilates", duration: 30, kcal: 130, date: "May 22", intensity: "Low", notes: "Core session" },
    { id: 7, type: "HIIT", duration: 22, kcal: 260, date: "May 21", intensity: "High", notes: "Short session, high effort" },
  ],
  symptoms: [
    { date: "May 26", symptoms: ["Fatigue"], severity: 2, notes: "Improved after breakfast" },
    { date: "May 25", symptoms: ["Headache", "Insomnia"], severity: 5, notes: "Screen-heavy workday" },
    { date: "May 23", symptoms: ["Back Pain"], severity: 3, notes: "After long sitting session" },
    { date: "May 21", symptoms: ["Dizziness", "Fatigue"], severity: 4, notes: "Skipped afternoon snack" },
    { date: "May 19", symptoms: ["Cough", "Sore Throat"], severity: 2, notes: "Likely allergies" },
  ],
};
